spring.application.name=api-gateway
server.port=8080
spring.cloud.gateway.server.webflux.routes[0].id=kunden-service
spring.cloud.gateway.server.webflux.routes[0].uri=${KUNDEN_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/kunden/**
spring.cloud.gateway.server.webflux.routes[1].id=bestellung-service
spring.cloud.gateway.server.webflux.routes[1].uri=${BESTELLUNG_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/bestellungen/**